package problem

const (
	TOPIC_ARRAY                = "array"
	TOPIC_HASH_TABLE           = "hash-table"
	TOPIC_LINKED_LIST          = "linked-list"
	TOPIC_MATH                 = "math"
	TOPIC_TWO_POINTERS         = "two-pointers"
	TOPIC_STRING               = "string"
	TOPIC_BINARY_SEARCH        = "binary-search"
	TOPIC_DIVIDE_AND_CONQUER   = "divide-and-conquer"
	TOPIC_DYNAMIC_PROGRAMMING  = "dynamic-programming"
	TOPIC_BACKTRACKING         = "backtracking"
	TOPIC_STACK                = "stack"
	TOPIC_HEAP                 = "heap"
	TOPIC_GREEDY               = "greedy"
	TOPIC_SORT                 = "sort"
	TOPIC_BIT_MANIPULATION     = "bit-manipulation"
	TOPIC_TREE                 = "tree"
	TOPIC_DEPTH_FIRST_SEARCH   = "depth-first-search"
	TOPIC_BREADTH_FIRST_SEARCH = "breadth-first-search"
	TOPIC_UNION_FIND           = "union-find"
	TOPIC_GRAPH                = "graph"
	TOPIC_DESIGN               = "design"
	TOPIC_TOPOLOGICAL_SORT     = "topological-sort"
	TOPIC_TRIE                 = "trie"
	TOPIC_BINARY_INDEXED_TREE  = "binary-indexed-tree"
	TOPIC_SEGMENT_TREE         = "segment-tree"
	TOPIC_BINARY_SEARCH_TREE   = "binary-search-tree"
	TOPIC_RECURSION            = "recursion"
	TOPIC_BRAINTEASER          = "brainteaser"
	TOPIC_MEMOIZATION          = "memoization"
	TOPIC_QUEUE                = "queue"
	TOPIC_MINIMAX              = "minimax"
	TOPIC_RESERVOIR_SAMPLING   = "reservoir-sampling"
	TOPIC_ORDERED_MAP          = "ordered-map"
	TOPIC_GEOMETRY             = "geometry"
	TOPIC_RANDOM               = "random"
	TOPIC_REJECTION_SAMPLING   = "rejection-sampling"
	TOPIC_SLIDING_WINDOW       = "sliding-window"
	TOPIC_LINE_SWEEP           = "line-sweep"
	TOPIC_ROLLING_HASH         = "rolling-hash"
	TOPIC_SUFFIX_ARRAY         = "suffix-array"
)
